### ISSUE TITLE
Reactivate shared wallet functionality

### ISSUE THREAD

**Issue by yaryribero** [dagcoin/dagcoin#160]
We need to reactivate the same feature byteball has allowing an user to create a shared wallet

**Comment by vkolt** [comment]
New created wallet does not appears on menu, so user can not switch wallets

**Comment by vkolt** [comment]
Wallet name at creation doesn't fit if long enough (check wallet information in wallet preferences)

**Comment by vkolt** [comment]
Should be possibility to delete wallet

**Comment by dkostenevich** [comment]
fixed #162

**Comment by vkolt** [comment]
![Screen Shot 2017-08-12 at 11.07.33.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b772b6455f16b7191a379ee0c2b56415c4dbe5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5e34aa984ec85af349e44e50a5143060f43b.png)

Happens if I'm going to delete wallet page and then click back button

**Comment by dkostenevich** [comment]
back button fixed #164
