### ISSUE TITLE
Research: encrypt .sqlite files and anything else that might contain privacy sensitive data using passphrase

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#270]
Currently the passphrase is used to encrypt the private key.

However, even ignoring the private key, there seems to be data contained in the .sqlite files that can reveal potentially private or identifying details about the owner of the wallet.

Ideally, if an attacker can get a copy of the byteball data files but does not have the passphrase for the wallet/private key, there is no other sensitive or potentially deanonymizing data revealed to the attacker.

Obviously, the wallet would need to decrypt the db before use, providing an attack opportunity, but the security of the db "at rest" would be improved - realistically most users have the wallet app open only a tiny percentage of the time.

## Acceptance criteria
* Research do we need it?
* what solution could be?
* how we can use same password?

**Comment by fishera123** [comment]
there are encryption options in sqlite that need to be explored.

**Comment by ilagin** [comment]
Considering that we would encrypt .sqlite files using already existing password protected zip-archive mechanism we'll have to solve 2 big challenges:
* Handle application close including crashes and process termination (which is not quite possible to handle)
* Handle the situation when zip archive is not yet created and .sqlite files are removed. This might potentially happen and this will lead to data loss.

Another option might be to use 3rd party sqlite database encryption tools. The SQLite Encryption Extension for example. This should be further investigated as it seems to be quite difficult to modify byteball core to operate with SEE. Plus the fact that SEE costs around 2k USD.

In Windows it is possible to encrypt sqlite databases by default. But due to the fact that we are using nodejs we'll have to use some 3rd party sqlite cipher.
Below are several links on sqlite cipher usage in node js:
https://www.npmjs.com/package/sqlite-cipher
https://coolaj86.com/articles/building-sqlcipher-for-node-js-on-raspberry-pi-2/
https://github.com/mapbox/node-sqlite3#building-for-sqlcipher

The option with 3rd party cipher sounds more realistic at the moment
