### ISSUE TITLE
implement conditional payments

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#314]
Expected behaviour:
For now, users can only send transactions. This task implies that users can bound condition to the payment.  The scope of this task is to have simple cases covered like lending money where you can set date when the money will be back. Conditions should be human readable and easy to create.

**Comment by vkolt** [comment]
After conditional payment is sent chat on both devices could not be opened anymore

**Comment by vkolt** [comment]
Conditional payment was sent , condition was completed, but other device didn't receive coins

**Comment by vkolt** [comment]
Error that happens when I tried to send coins form smart wallet
![Screen Shot 2017-12-14 at 23.12.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/595f9b04705d35001a11afd7/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c57e0b76216455f76b7191a37aec0c2a53415f46be5d4a1f06a3a3dc78e2a436628f550fe4d66d5c25933517a5b1d61fbf03bc73df4680b7e89850d2aa6c7bb3d4d216744b470a83ed5c3caa984ec95bf443e44451ad173667f43b.png)
