### ISSUE TITLE
funding node shouldn't be removable from paired devices 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#434]
user shouldn't be able to remove funding node from paired devices

**Comment by deaoja** [comment]
When wallet is created funding node is automatically paired with wallet, it is displayed in paired devices and user is currently able to remove it from the list manually. We should disable the ability to remove it from paired devices as otherwise the wallet can not make transactions using funding node any longer.

Solution is  to change the logic so that funding node can not be deleted. This is a temporary solution before building state machine, once state machine is aware the funding node is removed and will take needed action (or will just not give ability to delete without choosing another one immediately).

**Comment by fishera123** [comment]
note: made also discovery service not removable
