### ISSUE TITLE
map all strings in the project and upload it in crowdin 

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#534]
## Expected Behavior

All strings that need translation should be uploaded on crowdin 
## Current Behavior

In task #428 we implemented wallet localization, in this task we should map all strings that either was missed or added later. 

## Your Environment

* Version used: v1.3.3
* Operating System and version (desktop or mobile): desktop and mobile

**Comment by dimuha** [comment]
Russian translation check:
- title ‘ACCEPT INVITATION’ is not translated;
- message ‘Tap the QR-code to copy its address. Share it with the sender via email or text.’;
- in Send placeholder=“DAG address” is not translated;
- in Send Receiver should be Получатель, instead of Приемник;
- in Детали транзакции Единица may be блок или элемент;
- title ‘ADD DEVICE’ is not translated;
- the same code is called ‘код сопряжения’ in invite new device and in error message for accept invitation it is ‘код привязки’ and menu item is called “Спаренные устройства“; I think all of them should be unified;
- add new wallet not translated titles: CREATE NEW WALLET, PLAIN WALLET, MULTIDEVICE WALLET;
- titles GLOBAL PREFERENCES, DEVICE NAME, LANGUAGE, BACKUP (+ info message on backup screen), RECOVERY, EXPORT, IMPORT (+ choose file button and No file chosen placeholder), ABOUT, TERMS OF USE (all terms of use are not translated), SESSION LOG;
- a bit strange looks subitem  “О” in the settings. We can name it like "Информация" or "О программе"

**Comment by RaikoM** [comment]
Send - send all message 'You are sending all your stable amount.'

**Comment by vkolt** [comment]
1. titles are not translated still, and I can not find it's strings on crowdin
2. Plain/Multidevice wallet still not present in crowdin
3. Terms and conditions
4. Dag address in Send placeholder
5. Chat recording (in chat)

**Comment by fishera123** [comment]
terms and conditions shouldn't be translated yet.

**Comment by vkolt** [comment]
1. Automatical messages in chat (payment request)
2. Payment request button and title in pop-up
3. Chat recording
