### ISSUE TITLE
Wallet list is case-sensitive

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#673]
Wallet list is case-sensitive

## Current Behavior
Wallet names are ordered:
	1. upper case
	2. lower case
	3. special characters in unknown order :)

![WalletOrderCaseSensitive2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46df95962f8797869dedba51875ce3911a4329602010aa3d75d7a164fd52690e050a1de853524d41f5fd802ca6b56d25825a02e4856d5f76c06e45a5bd834bad1da862da11d1e9e1d30695aa2f2ff58a88453f1b041e8ffd5932a49d48c851e406.PNG)
![WalletOrderCaseSensitive3.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a5cc2bd2b3ebf00135f12e9/125516c66e82c728ace21e0d46df95962f8797869dedba51875ce3911a4329602010aa3d75d6a164fd52690e050a1de853524d41f5fd802ca6b56d25825a02e4856d5f76c06e45a5bd834bad1da862da11d1e9e1d30695aa2f2ff58a88453f1b041e8ffd593ca29b4ec85be406.PNG)

## Environment
* Windows 10
* V1.4.0t Beta

## Expected Behavior
	• Wallet list is not case-sencitive
	• Wallets are in alphabetical order (english)
	• How should be order wallet list with special characters like äõüöšž s.o.?

**Comment by msinansahin** [comment]
Now, all character able to be used in wallet name, following are few examples

' new wallet ": }
...new wallet
__1234

when these are sorted, the wallets whose names start with ', . will be the first. Because their character codes are less than [a-zA-Z]. But the wallets whose names start with _ will be after [a-zA-Z]. The reason is character code number.

In order to sort properly there should be some rules. For example all wallet whose names start with punctuation marks will be the first, etc.

**Comment by irinadoros** [comment]
* Wallet list is not case-sencitive _OK
* Wallets are in alphabetical order (english) - OK
