### ISSUE TITLE
remove share button from receive page

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#726]
## Expected Behavior

IMHO in receive page will be better if we will have icon in the header instead of big button for sharing address.

## Current Behavior

Sharing address is presented as a button with doesn't look good in mobile versions. 

## Your Environment

* Version used: 1.4.0
* Operating System and version (desktop or mobile): Android

**Comment by irinadoros** [comment]
In branch issue-726 I can't see icon in the header... and I don't see the [Share wallet link] button as well..
But from UX side I think that button is better way to share the address, than small icon in the header. 
What is an aim of that view? 
1. User want to share his address - **more important**
2. Request a specific amount - **less important**

So, IMHO, we should do accent on the address sharing, because it is what want user to do on this view above all.

**Comment by irinadoros** [comment]
On mobile device user can see sharing icon on the header - OK
![walletaddrsharebutton](https://user-images.githubusercontent.com/35455231/35502197-e1b5b972-04e4-11e8-8b35-d037904a4187.png)

App has different icons for wallet link sharing and requesting a specific amount - NOK
![requestshare](https://user-images.githubusercontent.com/35455231/35502180-d0e1c78a-04e4-11e8-8bcd-0127c7ced0b2.png)
Android has a little bit different sharing icon as well, but I think it is not a problem.
![androidshare](https://user-images.githubusercontent.com/35455231/35502190-da9f6b9c-04e4-11e8-9ac6-b05f819b7ea3.png)

**Comment by irinadoros** [comment]
* share button moved to the header - OK
* no scroll bar - OK
* sharing is working - OK
