### ISSUE TITLE
User can’t insert decimal number with comma if he uses Windows 10

### ISSUE THREAD

**Issue by irinadoros** [dagcoin/dagcoin#749]
User can’t insert decimal number with comma if he uses Windows 10, for example 0,12345. He can use only dot for decimal numbers, for example 0.12345

## Steps to Reproduce 
Open wallet on Windows 10 -> Send -> try insert amount as a decimal number with dot and comma  -> it is not possible to insert number with comma.

<img width="317" alt="amountsymbolswin10" src="https://user-images.githubusercontent.com/35455231/35565638-04203478-05c7-11e8-8183-abc5837b720c.png">

On Android it works well:
![amountsymbolsandroid](https://user-images.githubusercontent.com/35455231/35565717-537bb326-05c7-11e8-9aa0-59730d31b497.png)

## Environment
•	1.4.1 testnet
•	Windows 10

## Expected Behavior
•	User can insert decimal number with dot to the amount field
* Phone lang settings is russian and decimal number with dot (only)

**Comment by msinansahin** [comment]
As a note: This case (allow , for decimal separator) does not occur in android when phone language is English.

**Comment by msinansahin** [comment]
@irinadoros @fishera123                                               
As far as I explored This issue can not be fixed unless the amount field type is changed to text field and write a keypress action in order to filter the characters (,+-). However, in this case, the keyboard is not switched to numbers.

A keypress event was tried to filter unwanted characters. But, at this time android did not catch the character code as required. Always returns 229 code.

Currently, the field's type is number and if any unwanted character is entered the field becomes red as invalid. I think it is enough :)

**Comment by irinadoros** [comment]
It is possible to insert the letter "e" or "E" to the amount field.

**Comment by irinadoros** [comment]
With windows 10 it is possible to insert only dot - OK
With windows 10 it is not possible anymore to insert coma "," or "e" or "E" or plus "+" or minus "-" - OK
local branch 749

**Comment by ilagin** [comment]
@irinadoros @fishera123 I'll try one more thing for android

**Comment by ilagin** [comment]
@irinadoros could you please test for android once again? the branch you should use is "task-749-EI"

**Comment by irinadoros** [comment]
With branch "task-749-EI" it doesn't work if mobile phone in russian. User still can insert numbers woth dot and coma - NOK.
@ilagin , @fishera123  May be we should leave it as it is? It seems like time what we spend is so big and problem is so small..
