### ISSUE TITLE
Analyze a fee problem

### ISSUE THREAD

**Issue by fishera123** [dagcoin/dagcoin#9]

**Comment by dagcoin1** [comment]
Main goals, what we need to solve with the fee problem:
1. We should build the whole architecture so that there isn't a need for additional byteball tx.
2. Whole architecture should be decentralised, so there will not be central point of failure parts.
3. It should be very secure solution.
4. End-customer should not notice that there are some byteballs involved.
5. It should be fast enough.

**Comment by yaryribero** [comment]
@dannybreal If the document I wrote addresses the requirements from Asse, you may move this ticket to done.
